
services:
  telegram-bot:
    image: ${DOCKER_USERNAME}/telegram-bot:latest
    container_name: telegram-bot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - LIBRETRANSLATE_URL=http://libretranslate:5000/translate
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/cocktail_cache?authSource=admin
    depends_on:
      - libretranslate
      - mongo
    networks:
      - bot-net

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=en,ru
    networks:
      - bot-net

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo-data:/data/db
    networks:
      - bot-net

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 telegram-bot-app
    networks:
      - bot-net

networks:
  bot-net:
    driver: bridge

volumes:
  mongo-data:
