name: Build, Test and Analyze

on:
  push:
    branches: [ "master", "CI" ] # Запускать при push в master или CI
  pull_request:
    branches: [ "master" ] # Запускать при pull request в master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Использовать последнюю версию Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '18'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: target/

  qodana:
    needs: build-and-test # Запускать после успешной сборки
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
